apiVersion: v1
kind: Service
metadata:
  name: contosoair
  namespace: sample-app-namespace-1731097326921
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: contosoair
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000